edit linkchecker verification step

diff --git a/.github/workflows/link-checker.yml b/.github/workflows/link-checker.yml
--- a/.github/workflows/link-checker.yml
+++ b/.github/workflows/link-checker.yml
@@ -10,5 +10,21 @@ jobs:
         id: lc
         with:
           args: --verbose --no-progress *.md
+      - name: Count broken links
+        run: |
+            cat ./lychee/out.md
+            broken_max=10
+            broken=$(grep "Errors..." ./lychee/out.md)
+
+            broken_count=$(echo "$Errors..." | wc -l)
+            if [ "$broken_count" -gt "$broken_max" ]; then
+                echo "Number of broken links (${broken_count}) exceeds maximum allowed number (${broken_max})."
+                echo "Broken links: "
+                echo "$broken"
+                exit 1
+            else
+                echo "Number of broken links (${broken_count}) less than or equal to maximum allowed number (${broken_max})."
+                exit 0
+            fi
       - name: Fail if there were link errors
         run: exit ${{ steps.lychee.outputs.exit_code }}
